server:
  port: 8081

spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:h2:mem:exchangedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false

exchange:
  api:
    base-url: ${EXCHANGE_API_BASE_URL:https://economia.awesomeapi.com.br/json/last}

management:
  endpoints:
    web:
      exposure:
        include: health
